name: pipeline

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  builder:
    name: builder
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install
        run: npm install
      - name: build
        run: npm run build

  tester:
    name: tester
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install
        run: npm install
      - name: test
        run: npm run test

  formatter:
    name: formatter
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install
        run: npm run format-check

  linter:
    name: linter
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: lint
        run: npm run lint
