name: Deploy to Azure Container Instance

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Build and push Docker image
      - uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }} 
      - run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/bots/nasabot:latest .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/bots/nasabot:latest